use sencrypt;
insert into documents(documentId,userID,documentData,enctype,doctime) values(111111,9d1fa129-a267-46b3-b7db-9c38d520f843,'Some data1 will be enc','SSKE','2015-11-24 07:00:00+0100');
insert into documents(documentId,userID,documentData,enctype,doctime) values(111112,9d1fa129-a267-46b3-b7db-9c38d520f843,'Some data2 will be enc','SSKE','2015-11-24 07:00:00+0100');
insert into documents(documentId,userID,documentData,enctype,doctime) values(111113,9d1fa129-a267-46b3-b7db-9c38d520f845,'Some data will be enc3','FHE','2015-10-22 07:00:00+0100');