<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sSKEEcore" nsURI="http://www.example.org/sSKEEcore" nsPrefix="sSKEEcore">
  <eClassifiers xsi:type="ecore:EClass" name="SSKEEncryptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="symmetricencryptor" lowerBound="1"
        eType="#//SymmetricEncryptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pseudorandomgenerator"
        lowerBound="1" eType="#//PseudoRandomGenerator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pseudorandomfunction" lowerBound="1"
        eType="#//PseudoRandomFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SSKEDecryptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pseudorandomgenerator"
        lowerBound="1" eType="#//PseudoRandomGenerator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pseudorandomfunction" lowerBound="1"
        eType="#//PseudoRandomFunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symmetricdecryptor" lowerBound="1"
        eType="#//SymmetricDecryptor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoRandomGenerator" abstract="true"
      interface="true">
    <eOperations name="generateKey" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eParameters name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PseudoRandomFunction" abstract="true"
      interface="true">
    <eOperations name="generateRandomPiece">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eParameters name="seed" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymmetricEncryptor" abstract="true"
      interface="true">
    <eOperations name="encrypt" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
      <eParameters name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SymmetricDecryptor" abstract="true"
      interface="true">
    <eOperations name="decrypt">
      <eParameters name="encryptedData" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AES" eSuperTypes="#//SymmetricEncryptor #//SymmetricDecryptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IV" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Mode" eType="#//BlockCipherModeOfOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BlockCipherModeOfOperation">
    <eLiterals name="CBC"/>
    <eLiterals name="CTR" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SSKEKeys">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyA" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyB" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyC" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SSKKeysTxt">
    <eOperations name="SSKeysTxt" eType="#//SSKEKeys">
      <eParameters name="sskekeys" eType="#//SSKEKeys"/>
    </eOperations>
    <eOperations name="saveToFile">
      <eParameters name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eOperations name="loadFromFile">
      <eParameters name="filePath" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sskekeys" lowerBound="1"
        eType="#//SSKEKeys"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SSKE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sskekeys" lowerBound="1"
        eType="#//SSKEKeys" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sskedecryptor" lowerBound="1"
        eType="#//SSKEDecryptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sskeencryptor" lowerBound="1"
        eType="#//SSKEEncryptor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SSKEKeysGenerator">
    <eOperations name="generateKeys" eType="#//SSKEKeys"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SSKKeysJson">
    <eOperations name="SSKeysJson" eType="#//SSKEKeys">
      <eParameters name="sskekeys" eType="#//SSKEKeys"/>
    </eOperations>
    <eOperations name="convertToJson"/>
    <eOperations name="loadFromJson"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sskekeys" lowerBound="1"
        eType="#//SSKEKeys"/>
  </eClassifiers>
</ecore:EPackage>
